import { Toaster } from '#/components/ui/sonner';
import { cn } from '#/lib/utils';
import type { Metadata } from 'next';
import { DM_Sans, Geist, Geist_Mono, Noto_Serif } from 'next/font/google';
import './globals.css';

const notoSerifHeading = Noto_Serif({
  subsets: ['latin'],
  variable: '--font-heading',
});

const dmSans = DM_Sans({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        'h-full',
        'antialiased',
        geistSans.variable,
        geistMono.variable,
        'font-sans',
        dmSans.variable,
        notoSerifHeading.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
